// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tddekqmbgffqbilvcbcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZGVrcW1iZ2ZmcWJpbHZjYmNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTk1MjcsImV4cCI6MjA2NTEzNTUyN30.2H4vPviWQq00xwLo-REHmt87NOsR0N3Eh5q_WM6SgGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);